// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmBzB5bNRJAt3q3DC8-W2D1o-JOHNSK_I',
    appId: '1:810131550865:web:e13011182bd13d18460530',
    messagingSenderId: '810131550865',
    projectId: 'healthy-life-dec71',
    authDomain: 'healthy-life-dec71.firebaseapp.com',
    storageBucket: 'healthy-life-dec71.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjDDXSR4TbOhald5UVfd5nxG2-y8JJa7Y',
    appId: '1:810131550865:android:2badc8641493ffe7460530',
    messagingSenderId: '810131550865',
    projectId: 'healthy-life-dec71',
    storageBucket: 'healthy-life-dec71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5ivtxe7xafbNTHB_tumwiMm7WQutNTgs',
    appId: '1:810131550865:ios:37eb31bb5227c3b2460530',
    messagingSenderId: '810131550865',
    projectId: 'healthy-life-dec71',
    storageBucket: 'healthy-life-dec71.appspot.com',
    iosClientId: '810131550865-s17n3uju9fs623513ngjchmgib7jsqfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
